FROM maven:3.9.16-eclipse-temurin-17 AS build

WORKDIR /app-build

COPY pom.xml .
COPY src .

RUN mvn clean package -DskipTests || true

FROM openjdk:17.0.2-jdk AS lancement

WORKDIR /app-lancement

COPY --from=build /app-build/target/*.jar /app-lancement/application.jar

ENTRYPOINT ["java", "-jar", "/app-lancement/application.jar"]
